name: sub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 1. 변수 출력
      env:
        NAME: "kobalja"
        ID: ${{ github.actor }}
        JOB: "백수"
        HUMAN: true
      run: | 
        echo "내 이름은 $NAME 입니다."
        echo "My Name is $NAME , My Id is $ID , My Job is $Job and this is $HUMAN"      
